---
abstract: 'MIME file type identification'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MIME-Detect
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Fcntl: '0'
  File::ShareDir: '0'
  Moo: '2'
  XML::LibXML: '1.70'
  perl: '5.020'
resources:
  bugtracker: https://github.com/Corion/MIME-Detect/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/MIME-Detect.git
version: '0.10'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
